name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cppcheck

      - name: Build main application
        run: |
          g++ -std=c++11 -I src -o main_app src/main.cpp src/math_utils.cpp src/string_utils.cpp
          echo "Running main_app:"
          ./main_app

      - name: Build and run tests
        run: |
          g++ -std=c++11 -I src -o test_driver tests/test_driver.cpp src/math_utils.cpp src/string_utils.cpp
          echo "Running test_driver:"
          ./test_driver

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --inconclusive --std=c++11 src tests
